name: "Setup"
description: "Install tools and setup the environment"
runs:
  using: composite
  steps:
    - uses: Azure/setup-helm@v3
      with:
        version: 3.10.0
    - name: helm login
      run: helm registry login ghcr.io/hypnopotamus/skillsmatrix --username ${{ github.repository_owner }} --password $GITHUB_TOKEN
      shell: sh
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    - run: npm install
      shell: sh
    - run: npm pkg set config.container.registry=ghcr.io/hypnopotamus/skillsmatrix config.container.npm.registry=https://github.com/hypnopotamus/skillsmatrix config.chart.repository=ghcr.io/hypnopotamus/skillsmatrix
      shell: sh
    - run: npm config set registry=https://registry.npmjs.org @skillsmatrix:registry=https://github.com/hypnopotamus/skillsmatrix //github.com/hypnopotamus/skillsmatrix/:_authToken $GITHUB_TOKEN --location project
      shell: sh