FROM node:18.12.0 AS build
COPY package.json package.json
COPY src src
COPY tsconfig.json tsconfig.json
COPY server.tsconfig.json server.tsconfig.json
COPY webpack.config.js webpack.config.js
COPY docker.npmrc .npmrc
RUN npm install
RUN npm run build

FROM node:18.12.0 AS run
COPY --from=build package.json package.json
COPY --from=build .npmrc .npmrc
COPY --from=build dist dist
RUN npm install --production

EXPOSE 80 443
ENV NODE_ENV=production
ENTRYPOINT [ "npm", "run", "serve" ]