services:
  container-registry:
    image: registry:latest
    restart: unless-stopped
    ports:
      - 5000:5000
  matrixdb:
    image: tinkerpop/gremlin-server
    restart: unless-stopped
    ports:
      - 8182:8182