on:
  push:
    branches: [ $default-branch ]
    paths:
      - ./api/**
  pull_request_target:
    branches: [ $default-branch ] 
    paths: 
      - ./api/**

jobs:
  cd:
    uses: ./.github/workflows/CI.yml
    with:
      path: ./api
    