on:
  push:
    branches:
      - master
    paths:
      - buildScripts/**
  pull_request_target:
    branches:
      - master
    paths: 
      - buildScripts/**

jobs:
  cd:
    uses: ./.github/workflows/CI.yml
    with:
      path: buildScripts
    