name: "Continuous Integration"
on:
  workflow_call:
    inputs:
      path:
        required: true
        type: string

env:
  CI: true

jobs:
  publish:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.path }}
    steps:
      - uses: actions/checkout@v3
      - name: "publish"
        uses: ./actions/publish